### ISSUE TITLE
Keeping source jars

### ISSUE THREAD

**Issue by danic-wd** [gradlex-org/extra-java-module-info#113]
Hi,

When using the plugin, after jar transformation, Intellij fails to download sources for transformed jars. Is there a workaround for this ?

Thanks

**Comment by jjohannes** [comment]
This may be a "new" problem because IntelliJ recently changed the mechanism of how it downloads sources. However, I can not reproduce the problem. I just tried it (IDEA 2023.3.4) and pressing _Download Sources_ works here for transformed Jars. 

Maybe it is another issue with a specific library? Maybe something similar to this: 
https://github.com/openjfx/javafx-gradle-plugin/issues/164

For which libraries are you having this problem? What is the error message?

**Comment by danic-wd** [comment]
This is typical. This has been bothering me for a while and after upgrading to 2023.3.5 and ticking the "advanced settings -> build tools, gradle, download sources" option I can't reproduce the issue any more. I guess now it's downloaded everything upfront. When I was seeing the error I couldn't find anything on the build or run windows (or in the idea log). It was just a UI notification pop up with very little info. Sorry for the noise.

**Comment by jjohannes** [comment]
Don't worry. These problems in the IDE are annoying and it is hard to figure out which of the tools/plugins involved are responsible. Happy to hear that it works for you now.
