### ISSUE TITLE
Empty jars created when Intellij refreshes project

### ISSUE THREAD

**Issue by kpagratis** [gradlex-org/extra-java-module-info#78]
[empty-jars.zip](https://github.com/gradlex-org/extra-java-module-info/files/13370275/empty-jars.zip)

When refreshing the attached gradle project, the plugin causes empty jars to be created.
Commenting out `extra-java-module-info` and re-refreshing intellij after a gradle clean results in no empty jars.

This is causing issues when using quarkus (I'll be creating an issue there as well) when it attempts to build and encounters a 0 byte jar.

**Comment by rteabeault** [comment]
I see this empty jar was added in https://github.com/gradlex-org/extra-java-module-info/issues/15. And this does cause issues with quarkus when it runs `quarkusGenerateCode` task. You get an error like 

```
Failed to read /somepath/build/libs/some-test-fixtures.jar
```

**Comment by jjohannes** [comment]
The issue that the transform (sometimes?) runs during the IDEA Sync (before Jar files are created) still exists. I am not sure if it is the case for all projects, but it is in this reproducer and it looks like a very general code path to me. So that's a problem with how transforms are triggered in the Gradle/IDEA integrations itself.

The change for #15 had two parts:
1. If the file does not exist, do not proceed - this alone should cater for the IDEA Sync issue
2. The reproducer in #15 used the `org.springframework.boot` plugin. Once I fixed (1) I saw that the plugin triggered a follow up error. So I added the code to create the empty Jar, which is the hacky bit. At that point I thought that there are probably more plugins (or build configurations) that may cause this situation.

I looked again at the original reproducer from #15 and reproduced the problem from back then. Then I updated the `org.springframework.boot` to the latest version - `3.1.5` (including updating Java version and Gradle as required).

After that, problem (2) was gone.

What I will do is keep the check if the files exists  (1) but remove creation of the empty Jar (2). With this change, the reproducer here does not have the Quarkus issue anymore.

**Comment by rteabeault** [comment]
Thanks @jjohannes! Any idea on when I new release with this will be available?

**Comment by jjohannes** [comment]
This is now released in `1.6`.

**Comment by jjohannes** [comment]
Today I discovered this issue in Gradle: https://github.com/gradle/gradle/issues/27372

Which you may hit if you combine this plugins with other plugins that uses the `Configuration.getElements()` functionality. 

In some cases, it is fine to disable this plugins functionality for certain "special" configurations:
https://github.com/gradlex-org/extra-java-module-info#how-do-i-deactivate-the-plugin-functionality-for-a-certain-classpath
